### ISSUE TITLE
Mobile view: Show "Show more" Button before "Add Object" Button (change order)

### ISSUE THREAD

**Issue by daria-sl** [globe-swiss/phaenonet-client#129]
In mobile view, the "show more" button seems to be "overlooked" by users. Probably, this is because this button is placed below the green buttons (e.g., "add object"). Is it maybe possible to change the order in mobile view (as soon as the screen is not wide enough anymore to show both buttons next to each other, as it is the case on larger screens)? @pgoellnitz do you think this would be a good idea? and if so, how much time would you have to invest in this approximately? looking forward to reading your thoughts :)

**Comment by pgoellnitz** [comment]
I think the button tends to be overlooked because it does not visually stand out against the background. I remember checking if this was a 'bug' but iirc this is how it was specified in the designs.

My suggestion would be to change the background of the button to make it more visible.

As for your suggestion, that's probably possible. However the buttons are aligned on top of each other because there is not enough space horizontally. So we would need a different button design. Not my preferred option with regards to maintenance effort however.

Best would be if we could add some draft designs here how this should look like.

**Comment by daria-sl** [comment]
**1. Desktop-View:**
![grafik](https://user-images.githubusercontent.com/65400300/108596849-e2ee9d80-7387-11eb-85e8-07cbff9d7fba.png)
- Make Logout and "mehr anzeigen"-Buttons white in the background
- add a horizontal space (red line) between them
- uniform green (vertical) space (goal: make the vertical space between the objects and the show-more-button smaller, so it equals the space between "Deutsch" and the logout-button)
- Add vertical space after the two bottons (blue line, see also next image)

![grafik](https://user-images.githubusercontent.com/65400300/108597278-80e26800-7388-11eb-8882-b1e1947dbad5.png)
- Blue space should be bigger than green space

**Comment by daria-sl** [comment]
**2. Mobile View:**
![grafik](https://user-images.githubusercontent.com/65400300/108597429-43320f00-7389-11eb-952f-aa9a25aef5da.png)
- all orange spaces should be equal (meaning: reduce space between objects and "show more"-button, reduce space between "show more"-button and "add object"-button")
- add vertical space below "add object"-button, or, if show-more-button is the only one, below this one (violet line)
- Violet space should be larger than space between title and objects (darkred line)

**Comment by daria-sl** [comment]
Additional information:
- edit-object-button and delete-object-button stay as they are in their colors

**Comment by daria-sl** [comment]
this issue is no longer relevant since design will be adapted in another way!
