### ISSUE TITLE
Configure Ranger Species (insects)

### ISSUE THREAD

**Issue by pgoellnitz** [globe-swiss/phaenonet-client#185]
Configure the new insects species for the rangers. (see also #172)

- [x]  add species configuration
- [x]  add translations (species + statistics)
- [x] optimize and add icons
- [ ] validate configuration by WSL

Open:

- [x]  define the new species to configure @daria-sl
- [x]  translate all new text @daria-sl
- [x]  icon pack of the map pins @daria-sl

**Comment by daria-sl** [comment]
Insect species to be introduced:

deutsch | französisch | italienisch
-- | -- | --
Buchengallmücke | Cécidomyie du hêtre | Cecidomia del faggio
Schwammspinner | Bombyx disparate | Bombice dispari
Waldameise | Fourmis des bois | Formica del legno

Additional Phenophases & their translations:

deutsch | französisch | italienisch
-- | -- | --
Aufwärmphase | Phase de réchauffement | Fase di riscaldamento
Ausaperung | Fonte des neiges | Scioglimento della neve
Sonnungstraube | Réveil printanier | Risveglio primaverile
Beutefang | Capture de proies | Cattura della preda
Jungfernflug | Vol nupital | Volo nuziale
Schlüpfzeitpunkt | Temps d'éclosion | Tempo di schiusa

Additional Phenophases' Descriptions & their translations (please ignore the quotes in some lignes, I had to add them because the table layout didn't work in GitHub if a line starts with ">"):

deutsch | französisch | italienisch
-- | -- | --
Erste Teile des Nests sind frei von Schnee | Certaines parties du nid sont déneigées | Alcune parti del nido sono ancora coperte di neve
">10 Individuen auf dem Nest bei sonnigen Bedingungen (Mittag) mit einem Suchaufwand von 20 Sekunden" | ">10 individus sur le nid par temps ensoleillé (midi) avec un effort de recherche de 20 secondes" | ">10 individui sul nido in condizioni di sole (mezzogiorno) entro un tempo di ricerca di 20 secondi"
Unzählige Individuen auf dem Nest formen sich zu Clustern bei sonnigen Bedingungen (Mittagszeit) | D'innombrables individus sur le nid sont regroupés en masse dans des conditions ensoleillées (midi) | Innumerevoli individui sul nido sono raggruppati in massa in condizioni di sole (mezzogiorno)
Mindestens ein zum Nest getragenes Beutetier (Insekt, Spinne, Tausendfüßler etc.) wird bei einem Suchaufwand von 20 Sekunden in der Nähe des Nestes entdeckt | Au moins une proie transportée vers le nid (insecte, araignée, mille-pattes, etc.) est détectée avec un effort de recherche de 20 secondes juste autour du nid | Almeno una preda portata al nido (insetto, ragno, millepiedi, etc.) viene rilevata entro un tempo di 20 secondi proprio intorno al nido
">10 geflügelte Individuen auf dem Nest sichtbar (Männchen und/oder Königinnen) mit einem Suchaufwand von 20 Sekunden (Vormittag)" | ">10 individus ailés visibles sur le nid (mâles et/ou reines) avec un effort de recherche de 20 secondes (matin)" | ">10 individui alati visibili sul nido entro un tempo di ricerca di 20 secondi"
Mindestens eine Raupe ist aus dem Ei geschlüpft | Au moins une chenille est sortie de l'œuf | Almeno un bruco si è schiuso
Mindestens eine adulte Mücke ist aus der Galle geschlüpft | Au moins un moustique adulte a éclos de la galle | Almeno una zanzara adulta si è schiusa dalla galla

**Comment by daria-sl** [comment]
assignment / structure of species and phenophases to be added:
[description_insect_species.txt](https://github.com/globe-swiss/phaenonet-client/files/7225159/description_insect_species.txt)

**Comment by daria-sl** [comment]
![waldameise](https://user-images.githubusercontent.com/65400300/134664860-c6671a2e-cdfa-4fb5-94a9-d374ea4c08ce.png)
![buchengallmücke](https://user-images.githubusercontent.com/65400300/134664863-0c9853ef-1d69-4b38-88d9-208b7845f7d1.png)
![schwammspinner](https://user-images.githubusercontent.com/65400300/134664865-9a772dc9-9d53-406c-971d-ac215fafac2f.png)

**Comment by pgoellnitz** [comment]
@daria-sl, colors were missing for the groups. I use gray (#f7f5f2) for all groups for now.
