### ISSUE TITLE
create pheno-year rollover function

### ISSUE THREAD

**Issue by pgoellnitz** [globe-swiss/phaenonet-client#36]
At any time of the year it must be possible to advance to the next 'pheno-year'.

- [x] empty individuals from the old pheno-year must be removed (to not clutter up the profile view)
- [x] firebase rules need to be evaluated dynamically
- [x] new pheno-year need to show up in map and statistics filter
- [x] observation limits need to work before and after new-year change
- [x] deleting observations/individuals of previous pheno-year (but in current calendar year) must not be possible
- [x] observations and individuals must be saved with the new pheno-year (!= calendar year)
- [x] statistic plots must support values outside of the selected calendar year
- [x] meteoswiss data is imported in the correct year
- [x]  batch processing of individual deletes
- [x]  restrict entry of dates not to enter dates in the future (after testing)
- [x]  check dependency to meteoswiss import with @daria-sl
- [ ]  setup dynamic configuration on production

**Comment by pgoellnitz** [comment]
@daria-sl, I recreated the test environment from production and triggered the rollover function to create phenoyear 2021. Please have a initial check if everything works as expected. The date limits for entering observations as still unlocked (possible to enter dates 1 year in the future)

**Comment by daria-sl** [comment]
Thank you for your work. I checked the dev environment. Here are my comments:
- in my profile, I can see new objects for phenoyear 2021 (which is good), they are also correctly placed as the first items in my profile view. However, I cannot edit them (I cannot add an observation) - but I think this is what you expected to happen, right?
- in my profile, I can edit the object from the phenoyear 2020 (which should not happen, if the phenoyear 2021 has started) - not sure if this is a real problem or just the case in this dev environment?
- I cannot enter an observation date in 2021 (if I try it at an object from 2020) - but you expected this, too, right?
- The analysis diagrams do not show the year 2021 as a possibility to select from the dropbown menu, I don't quite understand why. Same goes for the map view.
- because I can't enter an observation date and because I can't select 2021 for the analyses, I cannot check if the analysis diagrams would work properly when inserting, e.g., a date in 2020 belonging to phenoyear 2021
- I wouldn't know how to check if the MeteoSwiss data is imported correctly... I have to trust you there ;-)
- question concerning the images: will my hazel tree in 2020 keep the picture it had, if I update the picture in 2021? Just to know if you thought of this case and what would be your proposition?

**Comment by pgoellnitz** [comment]
@daria-sl, I'm very sorry. You'll need to check again there was a mixup in the versions to test.

**Comment by daria-sl** [comment]
@pgoellnitz no problem. Now everything worked fine! The only point left to do is, as we discussed this morning, check with MeteoSwiss when they switch the phenoyear. Apart from that, I'd say we're ready for deployment =)

**Comment by pgoellnitz** [comment]
The meteoswiss import should be fine as they include the reference year in their data for observations.
