### ISSUE TITLE
Users can modify their email adress

### ISSUE THREAD

**Issue by pgoellnitz** [globe-swiss/phaenonet-client#7]
Users can change their mail adress on the edit profile screen.

**Comment by daria-sl** [comment]
Hi, I just tested this functionality with the link you provided. Thank you for your work! Here are my remarks for discussion:

- Why is the old e-mail address automatically shown in the first line, although it says "new email"? Can we prevent this autofill, or maybe add another line above stating "Alte Mailadresse" or sth similar?
- Why is the password shown below? I think we should not display it, since in this window, we want to change our e-mail and not our password - for me it was confusing to see my password there
- The change worked well; I could login thereafter with my new email
- I received an email to my old adress stating that my sign-in email had been changed (which is good). However, when I clicked the link in the mail to "reset" my changes, the following message appeared:

![Foto 21-1-21, 10 33 18](https://user-images.githubusercontent.com/65400300/105332485-f49c2400-5bd4-11eb-830f-80b6de0b9500.png)

I also tried again but this did not work. Maybe because prior to clicking the link I had already signed in with my new email adress?

**Comment by pgoellnitz** [comment]
Hi @daria-sl,

1. good point, I'll rename the internal field name so it won't trigger autofill. As for the text and layout that's up to you. I believe it's important to be clear that the user is changing his login credential.
2. The password is needed because you need to re-authenticate (login again) to change your email address. I also think it's weird. Feel free to define the flow you want - but you will need to provide these credentials in most cases.
3. good
4. yes, I'll need to check that. In general is the message functionality ok? The same restrictions as always apply, we cannot change the message text itself and only set one language for all.

**Comment by pgoellnitz** [comment]
Both remaining issues should be fixed.
Waiting for finalized texts and translations.

**Comment by daria-sl** [comment]
Hi @pgoellnitz , I put my comments here although I already sent them via email - correcting some of the statements (since I realized that one of my email accounts automatically redirected to the other, which confused me^^) and adding a new point that just came to my mind:

- This time, I succeeded in resetting the change. However, it was strange to receive the email with the possibility to reset not to my email adress, which I signed in with today, but rather to my "original email adress" which I had used before I changed the mail for the first time some days ago. So the login still only worked with the changed email (which was in my case axolotl@gmx.ch) but I got the notification on daria.lehmann@students.unibe.ch (which had been the original adress before all trials of change).
- Also, when setting back the change, my original address was set instead of axolotl@gmx.ch. This looks to me like there might be a problem if people change their email more than once?
- Then I thought that maybe I should retry this all with a new registration to be sure - but unfortunately, in the test version you sent me, I can not register newly - if I click on "Noch keinen Account? Jetzt registrieren!", I automatically get redirected to the map view and the popup "Registrierung erfolgreich" appears at the bottom of the page - but I did not have a possibility to change my registration data^^ so maybe this test version is not suitable therefore? Or what am I doing wrong?
- Testing everything again, I realized that it would be good to add a "Cancel" button at the end of the window - but this concerns also the "edit password" and the "enter observation" windows and refers to https://github.com/globe-swiss/phaenonet-client/issues/16. I added it in the comments there.

**Comment by pgoellnitz** [comment]
Hi @daria-sl ,
1. I don't know about that. Might be some strategy to avoid exploiting this mechanic to take over an account. Also the old email address is reserved for some time and will not accept new registrations. It's the default behavior and probably a case of take it or leave it ;)
2. same as 1.
3. I can't reproduce this exact behavior. Could you explain step-by-step how to reproduce this? However I realized that we might end up in this loggedin/loggedout mixed state if you reset the mail while still logged in. We should resolve this #109 
4. Yes, but we should change all the dialogs to keep it consistent. Could you change #16 to reflect this and list all dialogs to change?

**Comment by daria-sl** [comment]
Hello @pgoellnitz 

1. alright. so let's take it ;-)
2. same
3. I can't reproduce it anymore either^^ so let's ignore this for the moment. However, this loggedin/-out mixed state should really be resolved I guess. I am still waiting for Aurele to send me his exact "reproducible case"...
4. I added a comment to https://github.com/globe-swiss/phaenonet-client/issues/16 already yesterday, so this is done.

Then: I received the translations for the e-mail change:


Deutsch | Französisch | Italienisch
-- | -- | --
'LOGIN E-MAIL ÄNDERN' | 'MODIFIER LE COURRIEL DE CONNEXION' | 'MODIFICA E-MAIL DI LOGIN'
'Neue E-Mail' | 'Nouveau courriel' | 'Nuova e-mail'
'Neue E-Mail bestätigen' | 'Confirmer le nouveau courriel' | 'Conferma della nuova e-mail'
'Aktuelles Passwort' | 'Mot de passe actuel' | 'Password attuale'
'Die E-Mails stimmen nicht überein.' | 'Les courriels ne correspondent pas.' | 'Le e-mail non corrispondono.'

**Comment by pgoellnitz** [comment]
- The mixed-up login state issues are hopefully fixed (#109)
- #16 I will not touch right now

Sorry looks like we'll need some more translations (some of them were missing before):

- E-Mail geändert
- Die E-Mail wurde erfolgreich geändert.
- PASSWORT ÄNDERN
- Passwort geändert
- Das Passwort wurde erfolgreich geändert.
- Passwort falsch
- Das eingegebene aktuelle Passwort ist falsch.
- Neues Passwort
- Neues Passwort bestätigen

**Comment by daria-sl** [comment]
Thank you! Here are the propositions for the translations:


**Deutsch** | **Französisch** | **Italienisch**
-- | -- | --
E-Mail geändert | Courriel modifié | E-mail modificata
Die E-Mail wurde erfolgreich   geändert. | Le courriel a été modifié   avec succès. | L'e-mail è stata   modificata con successo.
PASSWORT ÄNDERN | MODIFIER MOT DE PASSE | MODIFICA PASSWORD
Passwort geändert | Mot de passe modifié | Password modificata
Das Passwort wurde erfolgreich   geändert. | Le mot de passe a été   modifié avec succès. | La password è stata   modificata con successo.
Passwort falsch | Mot de passe incorrect | Password non corretta
Das eingegebene aktuelle   Passwort ist falsch. | Le mot de passe actuel saisi   est incorrect. | La password attuale   inserita non è corretta.
Neues Passwort | Nouveau mot de passe | Nuova password
Neues Passwort bestätigen | Confirmer nouveau mot   de passe | Conferma della nuova   password
