### ISSUE TITLE
Individuals can be removed by users

### ISSUE THREAD

**Issue by pgoellnitz** [globe-swiss/phaenonet-client#8]
Individuals can be removed by the owning user. Individuals should only be removed for the selected year.

If the individual has no observations it may be deleted. If it has observations then the data must be kept but the individual is not shown in the profile anymore.

Also unused uploaded images must be deleted when the individual is deleted.

Open @daria-sl: How and where should the deletion be triggered?

**Comment by daria-sl** [comment]
Löschen bestätigen
Möchten Sie diese Beobachtung wirklich löschen?
Löschen – Abbrechen

Confirmer la suppression
Souhaitez-vous vraiment supprimer cette observation ?
Supprimer – Annuler

Confermare la cancellazione
Vuole davvero cancellare  questa osservazione?
Cancella – **Annulla**

**Comment by pgoellnitz** [comment]
- Individuals will only be deleted for the current year. 
- Individuals from previous years will still remain in the profile.
- Delete button must not be displayed for individuals from previous years.
- (for now) only individuals without observations can be removed. Explanation will be given in the dialog.
- It may not be possible to restore deleted objects

Open questions @daria-sl:
- What dialogs are needed? (different cases like 'empty' individual, individual with observations, ...)
- screenshots, text, translations

**Comment by daria-sl** [comment]
Possibility to delete an object is shown on own object screen in the current year (where I could also enter an observation) with the following button:
![image](https://user-images.githubusercontent.com/65400300/83871826-0f4a8700-a731-11ea-921a-fa33f254602f.png)

If I press this button, there will be a pop-up window (A) or (B). (A) is shown, if there are no observations entered for this object in the current year, (B) is shown if there are observations available for the object in the current year.

Pop-up Window (A):
![image](https://user-images.githubusercontent.com/65400300/83872516-6f8df880-a732-11ea-9857-2d846c576a9e.png)

Pop-up Window (B):
![image](https://user-images.githubusercontent.com/65400300/83873450-2048c780-a734-11ea-9dda-dba9f5ed5861.png)

What do you think about this proposition @pgoellnitz ? If it is okay for you, I'll get the texts translated.

**Comment by pgoellnitz** [comment]
@daria-sl, ok. Waiting for translations.

**Comment by daria-sl** [comment]
TRANSLATIONS - @pgoellnitz I hope you can deal with the translations in this format, otherwise please let me know.

Deutsch
Französisch
Italienisch

OBJEKT LÖSCHEN
SUPPRIMER L’OBJET
ELIMINARE L'OGGETTO

Möchten Sie das Objekt definitiv löschen? In Zukunft können Sie keine Daten mehr zu diesem Objekt eingeben. Daten zu diesem Objekt aus vergangenen Jahren bleiben erhalten.
Souhaitez-vous vraiment supprimer l’objet ? Vous ne pourrez ensuite plus saisir d’observation pour cet objet. Celles des années précédentes seront par contre conservées.
Si vuole eliminare definitivamente l'oggetto? In futuro non sarà più possibile inserire dati riguardanti questo oggetto. I dati degli anni precedenti saranno comunque conservati.

Objekt löschen
Supprimer l’objet
Eliminare l'oggetto

LÖSCHEN NICHT MÖGLICH
SUPPRESSION IMPOSSIBLE
ELIMINAZIONE IMPOSSIBILE

Das Objekt kann nicht gelöscht werden, weil im aktuellen Jahr Beobachtungen erfasst wurden. Löschen Sie zuerst die Beobachtungen, um das Objekt löschen zu können. Wenn Sie die Beobachtungen im aktuellen Jahr behalten wollen, löschen Sie das Objekt erst im kommenden Jahr.

L'objet ne peut être supprimé car des observations de l'année en cours sont encore enregistrées. Supprimez d'abord les observations puis supprimez l'objet. Pour conserver les données de l'année en cours, attendez l'année prochaine pour supprimer l’objet.
L'oggetto non può essere eliminato perché sono ancora registrate osservazioni dell'anno in corso. Cancellare le osservazioni prima di eliminare l'oggetto. Se si vogliono conservare le osservazioni dell'anno in corso, attendere il prossimo anno per eliminare l'oggetto.

zurück zum Objekt
retour
indietro all'oggetto

Löschen fehlgeschlagen
Échec de la suppression
Eliminazione non riuscita

Das Objekt konnte nicht gelöscht werden.
L’objet n’a pas pu être supprimé.
Non è stato possibile eliminare l'oggetto.

Löschen erfolgreich
Objet supprimé
Oggetto eliminato con successo

Das Objekt wurde gelöscht.
L’objet a été supprimé.
L'oggetto è stato eliminato.

**Comment by daria-sl** [comment]
Test reveals that:

- basic functionality is good (object can be deleted; object cannot be deleted if there are observations in the current year; if observations in current year are deleted, object can be deleted)
- texts are correct in German, French and Italian and pop-up windows after action work well
- a deleted object is not shown on map anymore, which is great
- there is no notification if a user whom I follow deletes an object. I don't remember what we discussed there: should this maybe be introduced @pgoellnitz ?
- in order to delete an object, I deleted several observations from this object prior to deleting it. In the other profile, following "myself", I only got one notification for one phenophase, but I deleted 3 observation dates. Why is this? Normally, I would expect a notification for every deleted phenophase... Maybe the activities occurred too fast after one other?

**Comment by pgoellnitz** [comment]
For now we have not defined any activity when objects are deleted. Not sure how relevant this case is to you but if this should be implemented the look and content of that activity must be defined.

As for yoir 'notification' issue: You mean you didn't see all the 'activities' you would expect?
If that's the case there might be a race condition if the individual is deleted before all observations were processed. I thought of that but didn't follow up.
I'll check what can be done.

**Comment by daria-sl** [comment]
Allright. I'll create a new issue with the activity if an object is deleted, so we can finish up this one. The activity for the deletion of an object is not urgent, from my point of view, but would be "nice to have".

Exactly. Thanks =) If you can find an easy solution, then good, but don't loose too much time there: I don't think that this case is extremely relevant for users.

**Comment by pgoellnitz** [comment]
relates to globe-swiss/phaenonet-functions#37
